views/adobe.py
from flask import Blueprint, render_template, request
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import time

# Webscrapping of the Adobe stock photos page
# Provides the description of the pictures corresponding to the search query
# limited to the first result page
# the displayed lines can be used as prompts for generating AI image

# Create a blueprint for the Adobe functionality
adobe_bp = Blueprint('adobe', __name__, url_prefix='/scrape')

# Define constants
ADOBE_STOCK_IMAGES_URL = "https://stock.adobe.com/"
WEBSCRAPPER_SLEEP_INTERVAL = 1


# Function to initialize the Selenium WebDriver
def init_webdriver():
    # Setting up the Selenium WebDriver
    options = webdriver.ChromeOptions()
    options.add_argument('--headless')  # Run headless Chrome for better performance
    driver = webdriver.Chrome(options=options)
    return driver


# Function to scrape Adobe Stock Images using Selenium
def scrape_adobe_images(query):
    # print(f"Query: {query}")
    driver = init_webdriver()
    try:
        driver.get(ADOBE_STOCK_IMAGES_URL)
        time.sleep(WEBSCRAPPER_SLEEP_INTERVAL)

        # Find search box and enter search query
        search_box = driver.find_element(By.NAME, "keyword")
        search_box.clear()
        search_box.send_keys(query)
        search_box.send_keys(Keys.RETURN)

        # allow time for processing the return
        time.sleep(WEBSCRAPPER_SLEEP_INTERVAL)

        # get infomration about the images
        images = driver.find_elements(By.XPATH, "//img[@alt]")
        # for image in images:
        #     print(f'{image.get_attribute("alt")}{image.get_attribute("name")}\n')

        return images

    finally:
        # driver.quit()
        time.sleep(WEBSCRAPPER_SLEEP_INTERVAL)


# Route to handle Adobe scraping
@adobe_bp.route("/scrape", methods=["GET", "POST"])
def scrape():
    search_term = ""
    # print("scrape called")
    if request.method == "POST":
        # print("scrape post")
        search_term = request.form.get("topic")
        images = scrape_adobe_images(search_term)
        # for image in images:
        #     print(f'{image.get_attribute("alt")}{image.get_attribute("name")}\n')
        return render_template('adobe.html',
                               images=images,
                               topic=search_term)

    return render_template('adobe.html',
                           images=None,
                           topic=search_term)

views/character.py
from flask import Blueprint, render_template, request
from forms import CharacterForm
from utils import process_character_form_data

character_bp = Blueprint('character', __name__, url_prefix='/character')


@character_bp.route("/", methods=["GET", "POST"])
def character():
    form = CharacterForm()

    if request.method == "POST":
        prompt = process_character_form_data(request.form)

        # print(prompt)
        return render_template('character.html', form=form, prompt=prompt)

    # Render the template without a result if the form is not submitted
    return render_template('character.html', form=form)

views/generic.py
from flask import Blueprint, render_template, request
from forms import GenericForm
from utils import process_generic_form_data


generic_bp = Blueprint('generic', __name__, url_prefix='/generic')


@generic_bp.route("/", methods=["GET", "POST"])
def generic():
    form = GenericForm()
    # print("Generic called")

    if request.method == "POST":
        # if form.validate_on_submit():
        # Process form data to create the prompt
        prompt = process_generic_form_data(request.form)

        # print(prompt)
        return render_template('generic_refactored.html', form=form, result=prompt)

    # Render the template without a result if the form is not submitted
    return render_template('generic_refactored.html', form=form)

views/landscape.py
from flask import Blueprint, render_template, request
from forms import LandscapeForm
from utils import process_landscape_form_data


landscape_bp = Blueprint('landscape', __name__, url_prefix='/landscape')


@landscape_bp.route("/", methods=["GET", "POST"])
def landscape():
    form = LandscapeForm()

    if request.method == "POST":

        # Process form data to create the prompt
        prompt = process_landscape_form_data(request.form)

        # print(prompt)
        return render_template('landscape.html', form=form, prompt=prompt)

    # Render the template without a result if the form is not submitted
    return render_template('landscape.html', form=form)

templates/adobe.html
{% extends 'base.html' %}

{% block title %}Generic Prompt Generator for Generative Artificial Intelligence{% endblock %}

{% block content %}
<div class="container">
  <h1 class="heading">Welcome to the Adobe Stock Image Data Webscrapping Tool</h1>
  <p class="description">Enter a topic of your choice and when clicking the submit button, the tool will provide you with the description
  of the first 100 images in the Adobe Stock Image Database for use in prompt for image generative AI.</p>
</div>


    <a
      class="btn btn-warning btn-lg"
      href="{{ url_for('home') }}"
      role="button"
      >Back</a
    >


    <form method="POST" action="{{ url_for('adobe.scrape') }}">
        <div class="mb-3 row">
            <label for="topic">Topic:</label>
            <input type="text" id="topic" name="topic" value="{{ topic }}"><br><br>
        </div>
        <br><br>

        <button type="submit">Submit</button><br><br>

        <div class="row">
            <label for="images">List of image descriptions:</label>
            {% if images %}
                {% for image in images[3:-3] %}
                    {% set text_to_write = image.get_attribute("alt") %}
                    {% if text_to_write and text_to_write|length > 1 %}
                        <p>{{ text_to_write }}</p>
                    {% endif %}

                {% endfor %}
            {% else %}
                <p>No descriptions available.</p>
            {% endif %}
        </div>

        <br><br>


    </form>


{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    {% block styles %}
    <!-- Load Bootstrap-Flask CSS here -->
    {{ bootstrap.load_css() }}
    <!-- Link to the styles.css here to apply styling to all the child templates.-->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Nunito+Sans:300,400,700"
    />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Poppins:300,400,700"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
      integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog=="
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/styles.css') }}"
    />
    {% endblock %}

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    {% block content %}{% endblock %}
  </body>
</html>

templates/character.html
{% extends 'base.html' %}

{% block title %}Generic Prompt Generator for Generative Artificial Intelligence{% endblock %}

{% block content %}
<div class="container">
  <h1 class="heading">Welcome to the Science Fiction and Fantasy Character Prompt Generator</h1>
  <p class="description">Fill in the requested information and click generate. You can edit the prompt and send it to the clipboard to be used in other applications.</p>
</div>

    <form method="POST">
  {{ form.hidden_tag() }}  <!-- CSRF protection tag -->

        <div class="container">
          <div class="row">
            <div class="col-3">
                {{ form.scene.label(class="form-label") }}
                {{ form.scene(class="form-control", placeholder="scene") }}
           </div>
              <div class="col-3">
                {{ form.gender.label(class="form-label") }}
                {{ form.gender(class="form-control", placeholder="gender") }}
           </div>
          <div class="col-3">
                {{ form.race.label(class="form-label") }}
                {{ form.race(class="form-control", placeholder="race") }}
           </div>
           <div class="col-3">
                {{ form.body_type.label(class="form-label") }}
                {{ form.body_type(class="form-control", placeholder="body_type") }}
           </div>
          <div class="col-3">
                {{ form.skin.label(class="form-label") }}
                {{ form.skin(class="form-control", placeholder="skin") }}
           </div>

          </div>

        <div class="row">
          <div class="col-3">
                {{ form.hair_color.label(class="form-label") }}
                {{ form.hair_color(class="form-control", placeholder="hair_color") }}
           </div>
          <div class="col-3">
                {{ form.hair_type.label(class="form-label") }}
                {{ form.hair_type(class="form-control", placeholder="hair_type") }}
           </div>
            <div class="col-3">
                {{ form.clothing_color.label(class="form-label") }}
                {{ form.clothing_color(class="form-control", placeholder="clothing_color") }}
           </div>
                <div class="col-3">
                {{ form.clothing_material.label(class="form-label") }}
                {{ form.clothing_material(class="form-control", placeholder="clothing_material") }}
           </div>
            <div class="col-3">
                {{ form.clothing_type.label(class="form-label") }}
                {{ form.clothing_type(class="form-control", placeholder="clothing_type") }}
           </div>

        </div>

        <div class="row">
          <div class="col-3">
            {{ form.body_pose.label(class="form-label") }}
            {{ form.body_pose(class="form-control", placeholder="body_pose") }}
          </div>
          <div class="col-3">
                {{ form.tool_action.label(class="form-label") }}
                {{ form.tool_action(class="form-control", placeholder="tool_action") }}
           </div>
          <div class="col-3">
                {{ form.tool.label(class="form-label") }}
                {{ form.tool(class="form-control", placeholder="tool") }}
           </div>
        </div>

        <div class="row">
          <div class="col-md-2">
                {{ form.activity.label(class="form-label") }}
                {{ form.activity(class="form-control", placeholder="activity") }}
           </div>
           </div>
           <div class="col-md-4">
                {{ form.activity_detail.label(class="form-label") }}
                {{ form.activity_detail(class="form-control", placeholder="activity_detail") }}
           </div>
       </div>

        <div class="row">
                 <div class="col-md-1">

                </div>
            <div class="col-md-6">
                {{ form.background.label(class="form-label") }}
                {{ form.background(class="form-control", placeholder="background") }}
                <br><br>
            </div>
        </div>


        </div>

        <br>

         <div class="container">
            <div class="row">
                <div class="col">
                    <button type="submit">Generate Prompt</button><br>
                </div>
                <div class="col">
                    <button type="button" onclick="randomizeParameters()" disabled="disabled">Randomize</button><br><br>
                </div>
            </div>
        </div>
    </form>

    <div class="container">
{% if prompt %}
    <label for="generatedPrompt"><strong>Generated Prompt:</strong></label><br>
    <textarea id="generatedPrompt" rows="4" cols="150">{{ prompt }}</textarea><br><br>
    <button onclick="copyToClipboard()">Copy to Clipboard</button>
{% endif %}
    <br><br>
    <a
      class="btn btn-warning btn-lg"
      href="{{ url_for('home') }}"
      role="button"
      >Back</a
    >
    </div>

    <script>
    function randomizeParameters() {}

    function copyToClipboard() {
        const promptText = document.getElementById("generatedPrompt").value;
        navigator.clipboard.writeText(promptText).then(function() {
            alert("Prompt copied to clipboard!");
        }, function(err) {
            alert("Failed to copy prompt. Please try again.");
        });
    }

    </script>
{% endblock %}

templates/generic.html
{% extends 'base.html' %}

{% block title %}Generic Prompt Generator for Generative Artificial Intelligence{% endblock %}

{% block content %}
<div class="container">
  <h1 class="heading">Welcome to the Generic Prompt Generator</h1>
  <p class="description">Fill in the requested information and click generate. You can edit the prompt and store it to the clipboard.</p>
</div>

    <form method="POST" action="/basic">
        <div class="mb-3 row">
            <label for="subject">Subject:</label>
            <input type="text" id="subject" name="subject" value="{{ subject }}"><br><br>
        </div>

        <div class="mb-3 row">
            <label for="background">Background:</label>
            <input type="text" id="background" name="background" value="{{ background }}"><br><br>
        </div>


        <div class="container">

          <div class="row">
            <div class="col">
                <label for="style">Style:</label>
                <select id="style" name="style">
                {% for style_option in styles %}
                    <option value="{{ style_option }}" {% if style_option == style %}selected{% endif %}>{{ style_option }}</option>
                {% endfor %}
                </select><br><br>
           </div>

            <div class="col">
                <label for="camera_angle">Camera Angle:</label>
                <select id="camera_angle" name="camera_angle">
                    {% for camera_angle_option in camera_angles %}
                        <option value="{{ camera_angle_option }}" {% if camera_angle_option == camera_angle %}selected{% endif %}>{{ camera_angle_option }}</option>
                    {% endfor %}
                </select><br><br>
            </div>


            <div class="col">
                <label for="art_type">Art Type:</label>
                <select id="art_type" name="art_type">
                    {% for art_type_option in art_types %}
                        <option value="{{ art_type_option }}" {% if art_type_option == art_type %}selected{% endif %}>{{ art_type_option }}</option>
                    {% endfor %}
                </select><br><br>
            </div>
          </div>

          <div class="row">
            <div class="col">
                <label for="lighting">Lighting:</label>
                <select id="lighting" name="lighting">
                    {% for lighting_option in lightings %}
                        <option value="{{ lighting_option }}" {% if lighting_option == lighting %}selected{% endif %}>{{ lighting_option }}</option>
                    {% endfor %}
                </select><br><br>
            </div>

            <div class="col">
                <label for="color_palette">Color Palette:</label>
                <select id="color_palette" name="color_palette">
                    {% for color_palette_option in color_palettes %}
                        <option value="{{ color_palette_option }}" {% if color_palette_option == color_palette %}selected{% endif %}>{{ color_palette_option }}</option>
                    {% endfor %}
                </select><br><br>
            </div>

            <div class="col">
                <label for="color_vibe">Color Vibe:</label>
                <select id="color_vibe" name="color_vibe">
                    {% for color_vibe_option in color_vibes %}
                        <option value="{{ color_vibe_option }}" {% if color_vibe_option == color_vibe %}selected{% endif %}>{{ color_vibe_option }}</option>
                    {% endfor %}
                </select><br><br>
            </div>
        </div>

      <div class="row">
        <div class="col">
            <label for="composition">Composition:</label>
            <select id="composition" name="composition">
                {% for composition_option in compositions %}
                    <option value="{{ composition_option }}" {% if composition_option == composition %}selected{% endif %}>{{ composition_option }}</option>
                {% endfor %}
            </select><br><br>
        </div>

        <div class="col">
            <label for="special_effect">Special Effect:</label>
            <select id="special_effect" name="special_effect">
                {% for special_effect_option in special_effects %}
                    <option value="{{ special_effect_option }}" {% if special_effect_option == special_effect %}selected{% endif %}>{{ special_effect_option }}</option>
                {% endfor %}
            </select><br><br>
        </div>

      <div class="col">
        <label for="miscellaneous">Miscellaneous:</label>
        <select id="miscellaneous" name="miscellaneous">
            {% for miscellaneous_option in miscellaneouss %}
                <option value="{{ miscellaneous_option }}" {% if miscellaneous_option == miscellaneous %}selected{% endif %}>{{ miscellaneous_option }}</option>
            {% endfor %}
        </select><br><br>
        </div>
      </div>
    </div>

        <button type="button" onclick="randomizeParameters()">Randomize</button><br><br>
        <button type="submit">Generate Prompt</button><br><br>
    </form>

{% if prompt %}
    <label for="generatedPrompt"><strong>Generated Prompt:</strong></label><br>
    <textarea id="generatedPrompt" rows="4" cols="50">{{ prompt }}</textarea><br><br>
    <button onclick="copyToClipboard()">Copy to Clipboard</button>
{% endif %}

    <script>
    function randomizeParameters() {

    const styleSelect = document.getElementById("style");
    const optionsStyle = styleSelect.options;
    const randomStyle = Math.floor(Math.random() * optionsStyle.length);
    styleSelect.selectedIndex = randomStyle;

    const cameraAngleSelect = document.getElementById("camera_angle");
    const optionsCameraAngle = cameraAngleSelect.options;
    const randomCameraAngle = Math.floor(Math.random() * optionsCameraAngle.length);
    cameraAngleSelect.selectedIndex = randomCameraAngle;


    const artTypeSelect = document.getElementById("art_type");
    const optionsArtType = artTypeSelect.options;
    const randomArtType = Math.floor(Math.random() * optionsArtType.length);
    artTypeSelect.selectedIndex = randomArtType;

    const lightingSelect = document.getElementById("lighting");
    const optionsLighting = lightingSelect.options;
    const randomLighting = Math.floor(Math.random() * optionsLighting.length);
    lightingSelect.selectedIndex = randomLighting;

    const colorPaletteSelect = document.getElementById("color_palette");
    const optionsColorPalette = colorPaletteSelect.options;
    const randomColorPalette = Math.floor(Math.random() * optionsColorPalette.length);
    colorPaletteSelect.selectedIndex = randomColorPalette;

    const colorVibeSelect = document.getElementById("color_vibe");
    const optionsColorVibe = colorVibeSelect.options;
    const randomColorVibe = Math.floor(Math.random() * optionsColorVibe.length);
    colorVibeSelect.selectedIndex = randomColorVibe;

    const compositionSelect = document.getElementById("composition");
    const optionsComposition = compositionSelect.options;
    const randomComposition = Math.floor(Math.random() * optionsComposition.length);
    compositionSelect.selectedIndex = randomComposition;

    const specialEffectSelect = document.getElementById("special_effect");
    const optionsSpecialEffect = specialEffectSelect.options;
    const randomSpecialEffect = Math.floor(Math.random() * optionsSpecialEffect.length);
    specialEffectSelect.selectedIndex = randomSpecialEffect;

    const miscellaneousSelect = document.getElementById("miscellaneous");
    const optionsMiscellaneous = miscellaneousSelect.options;
    const randomMiscellaneous = Math.floor(Math.random() * optionsMiscellaneous.length);
    miscellaneousSelect.selectedIndex = randomSpecialEffect;


}
    function copyToClipboard() {
        const promptText = document.getElementById("generatedPrompt").value;
        navigator.clipboard.writeText(promptText).then(function() {
            alert("Prompt copied to clipboard!");
        }, function(err) {
            alert("Failed to copy prompt. Please try again.");
        });
    }
    </script>

    <a
      class="btn btn-warning btn-lg"
      href="{{ url_for('home') }}"
      role="button"
      >Back</a
    >



{% endblock %}

templates/generic_refactored.html
{% extends 'base.html' %}

{% block title %}Generic Prompt Generator for Generative Artificial Intelligence{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h1>Generic Prompt Creator</h1>
          <p class="description">Fill in the requested information and click generate. You can edit the prompt and store it to the clipboard.</p>
        <!-- Form begins here -->
        <form method="POST">
            {{ form.hidden_tag() }}  <!-- CSRF protection tag -->

            <!-- Subject Field -->
            <div class="mb-3">
                {{ form.subject.label(class="form-label") }}
                {{ form.subject(class="form-control", placeholder="Enter subject") }}
                {% if form.subject.errors %}
                    <div class="text-danger">
                        {% for error in form.subject.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <!-- Background Field -->
            <div class="mb-3">
                {{ form.background.label(class="form-label") }}
                {{ form.background(class="form-control", placeholder="Enter background") }}
                {% if form.background.errors %}
                    <div class="text-danger">
                        {% for error in form.background.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <!-- Style Dropdown Field -->
            <div class="mb-3">
                {{ form.style.label(class="form-label") }}
                {{ form.style(class="form-select") }}
                {% if form.style.errors %}
                    <div class="text-danger">
                        {% for error in form.style.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <!-- Art Type Dropdown Field -->
            <div class="mb-3">
                {{ form.art_type.label(class="form-label") }}
                {{ form.art_type(class="form-select") }}
                {% if form.art_type.errors %}
                    <div class="text-danger">
                        {% for error in form.art_type.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <!-- Art TypeCamera Angle Dropdown Field -->
            <div class="mb-3">
                {{ form.camera_angle.label(class="form-label") }}
                {{ form.camera_angle(class="form-select") }}
                {% if form.camera_angle.errors %}
                    <div class="text-danger">
                        {% for error in form.camera_angle.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <!-- Lighting Dropdown Field -->
            <div class="mb-3">
                {{ form.lighting.label(class="form-label") }}
                {{ form.lighting(class="form-select") }}
                {% if form.lighting.errors %}
                    <div class="text-danger">
                        {% for error in form.lighting.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <!-- Color Palette Dropdown Field -->
            <div class="mb-3">
                {{ form.color_palette.label(class="form-label") }}
                {{ form.color_palette(class="form-select") }}
                {% if form.color_palette.errors %}
                    <div class="text-danger">
                        {% for error in form.color_palette.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <!-- Color Vibe Dropdown Field -->
            <div class="mb-3">
                {{ form.color_vibe.label(class="form-label") }}
                {{ form.color_vibe(class="form-select") }}
                {% if form.color_vibe.errors %}
                    <div class="text-danger">
                        {% for error in form.color_vibe.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <!-- Composition Dropdown Field -->
            <div class="mb-3">
                {{ form.composition.label(class="form-label") }}
                {{ form.composition(class="form-select") }}
                {% if form.composition.errors %}
                    <div class="text-danger">
                        {% for error in form.composition.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <!-- Special Effects Dropdown Field -->
            <div class="mb-3">
                {{ form.special_effect.label(class="form-label") }}
                {{ form.special_effect(class="form-select") }}
                {% if form.special_effect.errors %}
                    <div class="text-danger">
                        {% for error in form.color_vibe.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <!-- Miscellaneous Dropdown Field -->
            <div class="mb-3">
                {{ form.miscellaneous.label(class="form-label") }}
                {{ form.miscellaneous(class="form-select") }}
                {% if form.miscellaneous.errors %}
                    <div class="text-danger">
                        {% for error in form.miscellaneous.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <!-- Submit Button -->
            <div class="mb-3">
                {{ form.submit(class="btn btn-primary") }}
            </div>
        </form>

        <!-- Display processed result here -->
        {% if result %}
        <div class="alert alert-info mt-3">
           <label for="generatedPrompt"><strong>Generated Prompt:</strong></label><br>
           <textarea id="generatedPrompt" rows="4" cols="50">{{ result }}</textarea><br><br>
           <button onclick="copyToClipboard()">Copy to Clipboard</button>
        </div>
        {% endif %}



      <a class="btn btn-warning btn-lg"
      href="{{ url_for('home') }}"
      role="button">
          Back
      </a>



    <!-- Include Bootstrap JS for better user experience -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>

    <script>
        function copyToClipboard() {
        const promptText = document.getElementById("generatedPrompt").value;
        navigator.clipboard.writeText(promptText).then(function() {
            alert("Prompt copied to clipboard!");
        }, function(err) {
            alert("Failed to copy prompt. Please try again.");
        });
    }

    </script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block title %}Basic Image Prompt Generator for Generative Artificial Intelligence{% endblock %}

{% block content %}

<div class="container">
  <h1 class="heading">Welcome to the AI Prompt Generator</h1>
  <p class="description">Click on a topic button to access the given prompt generator. This tool will help you create great prompts.</p>
</div>

<a
  class="btn btn-warning btn-lg"
  href="{{ url_for('basic') }}"
  role="button"
  >Basic Generator</a
>
<br><br>

<a
  class="btn btn-warning btn-lg"
  href="{{ url_for('generic.generic') }}"
  role="button"
  >Generic Generator <i>(Refactored)</i></a
>
<br><br>

<a
  class="btn btn-warning btn-lg"
  href="{{ url_for('character.character') }}"
  role="button"
  >Character Generator</a
>
<br><br>

<a
  class="btn btn-warning btn-lg"
  href="{{ url_for('landscape.landscape') }}"
  role="button"
  >Landscape Generator</a
>
<br><br>

<a
  class="btn btn-info btn-lg"
  href="{{ url_for('adobe.scrape') }}"
  role="button"
  >Adobe Image Data Webscrapping</a
>
<br><br>


{% endblock %}